### ISSUE TITLE
NOMP Pool Not working

### ISSUE THREAD

**Issue by vr4dude316** [bitcoinxt/bitcoinxt#361]
Have the daemon/wallet built.  Trying to run on UNOMP pool.  Not able to start the coin

**Comment by dgenr8** [comment]
What are instructions to see this?

**Comment by vr4dude316** [comment]
i am not able to ssh to my box at the moment.  I will post the output of the pool start when available.  thanks for your reply.

**Comment by vr4dude316** [comment]
Here is the output when attempting to start pool.  All other SHA256 coins i have running work fine.  I've tried using the old "Legacy" address and cash addresses...

unomp@ubuntu:~/unomp$ node init.js
[2018-03-19 12:42:02.760] [INFO] [default] - New Relic
[2018-03-19 12:42:02.764] [DEBUG] [default] - NewRelic Monitor New Relic initiated
[2018-03-19 12:42:02.768] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:02.768] [DEBUG] [default] - POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
[2018-03-19 12:42:02.768] [INFO] [default] - Run Workers
[2018-03-19 12:42:03.811] [INFO] [default] - New Relic
[2018-03-19 12:42:03.816] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:03.817] [INFO] [default] - Run Workers
[2018-03-19 12:42:03.830] [INFO] [default] - Switching Setup Thread 1 Loading last proxy state from redis
[2018-03-19 12:42:03.840] [DEBUG] [default] - Pool bitcoin atom Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:03.841] [DEBUG] [default] - Pool bitcoin cash Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:03.964] [DEBUG] [default] - Master PoolSpawner Spawned 2 pool(s) on 4 thread(s)
[2018-03-19 12:42:04.066] [INFO] [default] - New Relic
[2018-03-19 12:42:04.074] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:04.075] [INFO] [default] - Run Workers
[2018-03-19 12:42:04.097] [INFO] [default] - Switching Setup Thread 2 Loading last proxy state from redis
[2018-03-19 12:42:04.112] [DEBUG] [default] - Pool bitcoin atom Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:04.113] [DEBUG] [default] - Pool bitcoin cash Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:04.348] [INFO] [default] - New Relic
[2018-03-19 12:42:04.353] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:04.353] [INFO] [default] - Run Workers
[2018-03-19 12:42:04.365] [INFO] [default] - Switching Setup Thread 3 Loading last proxy state from redis
[2018-03-19 12:42:04.374] [DEBUG] [default] - Pool bitcoin atom Thread 3 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:04.375] [DEBUG] [default] - Pool bitcoin cash Thread 3 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:04.407] [DEBUG] [default] - Pool bitcoin atom Thread 1 started for bitcoin atom [BCA] {sha256}
                                                Network Connected:      Mainnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   592540
                                                Current Connect Peers:  6
                                                Current Block Diff:     362866313.0146051
                                                Network Difficulty:     NaN
                                                Network Hash Rate:      2.53 PH
                                                Stratum Port(s):        3333, 3334, 3335
                                                Pool Fee Percent:       0%
                                                Block polling every:    1000 ms
[2018-03-19 12:42:04.412] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:04.421] [DEBUG] [default] - Pool bitcoin atom Thread 2 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:04.421] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:04.432] [DEBUG] [default] - Pool bitcoin atom Thread 3 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:04.433] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:04.640] [INFO] [default] - New Relic
[2018-03-19 12:42:04.648] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:04.649] [INFO] [default] - Run Workers
[2018-03-19 12:42:04.668] [INFO] [default] - Switching Setup Thread 4 Loading last proxy state from redis
[2018-03-19 12:42:04.687] [DEBUG] [default] - Pool bitcoin atom Thread 4 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:04.688] [DEBUG] [default] - Pool bitcoin cash Thread 4 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:04.728] [DEBUG] [default] - Pool bitcoin atom Thread 4 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:04.728] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:07.483] [DEBUG] [default] - Pool bitcoin atom Thread 2 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.207]

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
   [2018-03-19 12:42:07.585] [ERROR] [default] - Master PoolSpawner Fork 2 died, spawning replacement worker...
               ^
[2018-03-19 12:42:07.586] [ERROR] [default] - Master PoolSpawner Fork 0 died, spawning replacement worker...
[2018-03-19 12:42:07.582] [DEBUG] [default] - Pool bitcoin atom Thread 4 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.201]
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^
[2018-03-19 12:42:07.591] [ERROR] [default] - Master PoolSpawner Fork 1 died, spawning replacement worker...
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
[2018-03-19 12:42:07.594] [ERROR] [default] - Master PoolSpawner Fork 3 died, spawning replacement worker...
[2018-03-19 12:42:10.202] [INFO] [default] - New Relic
[2018-03-19 12:42:10.207] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:10.208] [INFO] [default] - Run Workers
[2018-03-19 12:42:10.220] [INFO] [default] - Switching Setup Thread 1 Loading last proxy state from redis
[2018-03-19 12:42:10.234] [DEBUG] [default] - Pool bitcoin atom Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.235] [DEBUG] [default] - Pool bitcoin cash Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.274] [DEBUG] [default] - Pool bitcoin atom Thread 1 started for bitcoin atom [BCA] {sha256}
                                                Network Connected:      Mainnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   592540
                                                Current Connect Peers:  6
                                                Current Block Diff:     362866313.0146051
                                                Network Difficulty:     NaN
                                                Network Hash Rate:      2.53 PH
                                                Stratum Port(s):        3333, 3334, 3335
                                                Pool Fee Percent:       0%
                                                Block polling every:    1000 ms
[2018-03-19 12:42:10.278] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:10.289] [DEBUG] [default] - Pool bitcoin atom Thread 1 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.207]
[2018-03-19 12:42:10.289] [DEBUG] [default] - Pool bitcoin atom Thread 1 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.201]
[2018-03-19 12:42:10.290] [DEBUG] [default] - Pool bitcoin atom Thread 1 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.210]
[2018-03-19 12:42:10.292] [DEBUG] [default] - Pool bitcoin atom Thread 1 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.204]
[2018-03-19 12:42:10.378] [INFO] [default] - New Relic
[2018-03-19 12:42:10.383] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:10.384] [INFO] [default] - Run Workers
[2018-03-19 12:42:10.389] [INFO] [default] - New Relic
[2018-03-19 12:42:10.394] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:10.394] [INFO] [default] - Run Workers
[2018-03-19 12:42:10.396] [INFO] [default] - Switching Setup Thread 4 Loading last proxy state from redis
[2018-03-19 12:42:10.406] [INFO] [default] - Switching Setup Thread 2 Loading last proxy state from redis
[2018-03-19 12:42:10.405] [INFO] [default] - New Relic
[2018-03-19 12:42:10.410] [DEBUG] [default] - Pool bitcoin atom Thread 4 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.410] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:10.411] [INFO] [default] - Run Workers
[2018-03-19 12:42:10.411] [DEBUG] [default] - Pool bitcoin cash Thread 4 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.415] [DEBUG] [default] - Pool bitcoin atom Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.415] [DEBUG] [default] - Pool bitcoin cash Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.423] [INFO] [default] - Switching Setup Thread 3 Loading last proxy state from redis
[2018-03-19 12:42:10.429] [DEBUG] [default] - Pool bitcoin atom Thread 4 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:10.429] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:10.435] [DEBUG] [default] - Pool bitcoin atom Thread 3 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.436] [DEBUG] [default] - Pool bitcoin cash Thread 3 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:10.438] [DEBUG] [default] - Pool bitcoin atom Thread 2 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:10.438] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:10.452] [DEBUG] [default] - Pool bitcoin atom Thread 3 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:10.452] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:11.491] [DEBUG] [default] - Pool bitcoin atom Thread 4 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.206]
[2018-03-19 12:42:12.942] [DEBUG] [default] - Master CLI CLI listening on port 17117

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16


/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^
/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
         TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
         ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

[2018-03-19 12:42:13.387] [ERROR] [default] - Master PoolSpawner Fork 3 died, spawning replacement worker...
/home/unomp/unomp/node_modules/bignum/index.js:108
[2018-03-19 12:42:13.388] [ERROR] [default] - Master PoolSpawner Fork 1 died, spawning replacement worker...
            throw new TypeError('Unspecified operation for type '
                  ^
[2018-03-19 12:42:13.397] [ERROR] [default] - Master PoolSpawner Fork 2 died, spawning replacement worker...
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
[2018-03-19 12:42:13.402] [ERROR] [default] - Master PoolSpawner Fork 0 died, spawning replacement worker...
[2018-03-19 12:42:13.496] [INFO] [default] - New Relic
[2018-03-19 12:42:13.501] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:13.501] [INFO] [default] - Run Workers
[2018-03-19 12:42:14.351] [DEBUG] [default] - Website Server Website started on 172.16.4.114:8080
[2018-03-19 12:42:14.509] [ERROR] [default] - Website bitcoin cash Could not dumpprivkey for bitcoin cash {"code":-5,"message":"Invalid Bitcoin address"}
[2018-03-19 12:42:15.979] [INFO] [default] - New Relic
[2018-03-19 12:42:15.984] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:15.985] [INFO] [default] - Run Workers
[2018-03-19 12:42:15.998] [INFO] [default] - Switching Setup Thread 2 Loading last proxy state from redis
[2018-03-19 12:42:16.007] [DEBUG] [default] - Pool bitcoin atom Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.012] [DEBUG] [default] - Pool bitcoin cash Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.040] [DEBUG] [default] - Pool bitcoin atom Thread 2 started for bitcoin atom [BCA] {sha256}
[2018-03-19 12:42:16.041] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start
[2018-03-19 12:42:16.057] [DEBUG] [default] - Pool bitcoin atom Thread 2 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.206]
[2018-03-19 12:42:16.057] [DEBUG] [default] - Pool bitcoin atom Thread 2 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.207]
[2018-03-19 12:42:16.057] [DEBUG] [default] - Pool bitcoin atom Thread 2 Authorized AbBARuAhmMwai5DcKPLXUHf2W1FSERDASq:x [10.200.200.201]

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
[2018-03-19 12:42:16.074] [ERROR] [default] - Master PoolSpawner Fork 1 died, spawning replacement worker...
[2018-03-19 12:42:16.103] [INFO] [default] - New Relic
[2018-03-19 12:42:16.110] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:16.111] [INFO] [default] - Run Workers
[2018-03-19 12:42:16.119] [INFO] [default] - New Relic
[2018-03-19 12:42:16.124] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:16.125] [INFO] [default] - Run Workers
[2018-03-19 12:42:16.126] [INFO] [default] - Switching Setup Thread 1 Loading last proxy state from redis
[2018-03-19 12:42:16.137] [INFO] [default] - Switching Setup Thread 4 Loading last proxy state from redis
[2018-03-19 12:42:16.139] [DEBUG] [default] - Pool bitcoin atom Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.140] [DEBUG] [default] - Pool bitcoin cash Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.145] [DEBUG] [default] - Pool bitcoin atom Thread 4 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.151] [DEBUG] [default] - Pool bitcoin cash Thread 4 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.162] [DEBUG] [default] - Pool bitcoin atom Thread 1 started for bitcoin atom [BCA] {sha256}
                                                Network Connected:      Mainnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   592540
                                                Current Connect Peers:  6
                                                Current Block Diff:     362866313.0146051
                                                Network Difficulty:     NaN
                                                Network Hash Rate:      2.53 PH
                                                Stratum Port(s):        3333, 3334, 3335
                                                Pool Fee Percent:       0%
                                                Block polling every:    1000 ms
[2018-03-19 12:42:16.163] [DEBUG] [default] - Switching Setup sha256 Setting proxy difficulties after pool start


/home/unomp/unomp/node_modules/bignum/index.js:108
/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
               throw new TypeError('Unspecified operation for type '
                  ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
[2018-03-19 12:42:16.176] [ERROR] [default] - Master PoolSpawner Fork 0 died, spawning replacement worker...
               ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
[2018-03-19 12:42:16.185] [ERROR] [default] - Master PoolSpawner Fork 3 died, spawning replacement worker...
[2018-03-19 12:42:16.295] [INFO] [default] - New Relic
[2018-03-19 12:42:16.300] [INFO] [default] - POSIX Not Installed
[2018-03-19 12:42:16.301] [INFO] [default] - Run Workers
[2018-03-19 12:42:16.313] [INFO] [default] - Switching Setup Thread 3 Loading last proxy state from redis
[2018-03-19 12:42:16.325] [DEBUG] [default] - Pool bitcoin atom Thread 3 Share processing setup with redis (127.0.0.1:6379)
[2018-03-19 12:42:16.325] [DEBUG] [default] - Pool bitcoin cash Thread 3 Share processing setup with redis (127.0.0.1:6379)

/home/unomp/unomp/node_modules/bignum/index.js:108
            throw new TypeError('Unspecified operation for type '
                  ^
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/unomp/unomp/node_modules/bignum/index.js:108:19)
    at Object.base58.decode (/home/unomp/unomp/node_modules/merged-pooler/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/unomp/unomp/node_modules/merged-pooler/lib/util.js:277:26)
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:556:37
    at /home/unomp/unomp/node_modules/merged-pooler/lib/pool.js:558:15
    at /home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:134:13
    at parseJson (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/unomp/unomp/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
[2018-03-19 12:42:16.337] [ERROR] [default] - Master PoolSpawner Fork 2 died, spawning replacement worker...
^Cunomp@ubuntu:~/unomp$

**Comment by dgenr8** [comment]
Since I'm totally unfamiliar with unomp, you will have to describe the problem in terms of what it is asking XT to do, what it expects XT to do, and what XT actually did.  From the log though it looks like you have a BTC chain, not cash.  If you are re-using an existing data directory you need to launch XT with the -reindex option one time and wait for the reindex to complete (days).

**Comment by vr4dude316** [comment]
when I getnewaddress, i received a cash address.

**Comment by dgenr8** [comment]
Right.  XT launches in cash mode by default, but needs to be told to reindex the first time it runs with an old data directory.

**Comment by dagurval** [comment]
You can disable cash addresses by adding cashaddr=0 to bitcoin.conf

**Comment by vr4dude316** [comment]
no luck.  still running cashaddress  thanks for the tip though

**Comment by dagurval** [comment]
Sorry, the parameter is usecashaddr=0

**Comment by vr4dude316** [comment]
That was the trick.  Pool is starting now….

Mr. Chris Staples
Manager, Information Systems
Marist School
3790 Ashford Dunwoody Rd
Atlanta, GA 30319
770.936.6403
staplesc@marist.com
