### ISSUE TITLE
bitcoind aborts if bitcoin.conf doesn't exist

### ISSUE THREAD

**Issue by dagurval** [bitcoinxt/bitcoinxt#381]
```
$ ./src/bitcoind 
Error: Error: No rpcpassword set
Error: Unable to start HTTP server. See debug log for details.
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted
```

Log contents:
```
2018-04-12 06:56:00 Bitcoin XT version v0.11.0I-fcdbd2c7-dirty (2018-04-11 19:16:56 -0700)
2018-04-12 06:56:00 Using OpenSSL version OpenSSL 1.1.0f  25 May 2017
2018-04-12 06:56:00 Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
2018-04-12 06:56:00 Default data directory /home/dagurval/.bitcoin
2018-04-12 06:56:00 Using data directory /home/dagurval/.bitcoin
2018-04-12 06:56:00 Using config file /home/dagurval/.bitcoin/bitcoin.conf
2018-04-12 06:56:00 Using at most 125 connections (1024 file descriptors available)
2018-04-12 06:56:00 Using 4 threads for script verification
2018-04-12 06:56:00 scheduler thread start
2018-04-12 06:56:00 HTTP: creating work queue of depth 16
2018-04-12 06:56:00 Error: No rpcpassword setError: Error: No rpcpassword set
2018-04-12 06:56:00 Error: Unable to start HTTP server. See debug log for details.
2018-04-12 06:56:00 Shutdown: In progress...
2018-04-12 06:56:00 scheduler thread interrupt
2018-04-12 06:56:17 
```

**Comment by jeffgran** [comment]
Looking through the code it seems like this is intended behavior. It looks like it's trying to prevent you from accidentally starting it with no password since that would be a big security risk.

What do you think is the expected behavior here? Should we just check earlier in the initialization process and give a nicer error message? How nice? Like, link to the docs nice or just "cannot continue without an rpcpassword set"? Maybe disable this check for testnet mode?

**Comment by dagurval** [comment]
The error message is okay, however, there is an exception that is uncaught and it causes the program to abort. We want it to exit clean.

I checked the stacktrace now:
```
$ gdb ./src/bitcoind
(gdb) r
(gdb) bt                                      
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4e8f801 in __GI_abort () at abort.c:79
#2  0x00007ffff58828fb in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5888d3a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5888d95 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5888fe8 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff5884a89 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff58b49d0 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x000055555578874a in StopHTTPServer () at httpserver.cpp:505
#9  0x00005555555ad671 in Shutdown () at init.cpp:182
#10 0x000055555559be9a in AppInit (argc=<optimized out>, argv=<optimized out>) at bitcoind.cpp:173
#11 0x0000555555590aff in main (argc=1, argv=0x7fffffffde28) at bitcoind.cpp:185
(gdb) 
```

So `std::thread::join()` is throwing a `std::system_error`. We need to either figure out why it's throwing and fix that, or if it has a reason to, catch and log the exception in either StopHTTPServer, Shutdown or AppInit.
